[tool.poetry]
name = "atomic-red-team"
version = "0.1.0"
description = ""
authors = ["Maintainers <opensource@redcanary.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0"
jsonschema = "^4.25.0"
requests = "^2.32.5"
ruamel-yaml = "^0.18.14"
pydantic = "^2.11.7"
typer = "^0.16.0"
hypothesis = "^6.137.3"
pytest = "^8.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
