[tool.poetry]
name = "atomic-red-team"
version = "0.1.0"
description = ""
authors = ["Maintainers <opensource@redcanary.com>"]
readme = "README.md"
packages = [
    { package = "atomic_red_team", from = "." }
]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"
jsonschema = "^4.21.1"
requests = "^2.31.0"
ruamel-yaml = "^0.18.6"
pydantic = "^2.7.0"
typer = "^0.12.3"
hypothesis = "^6.100.0"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
