[tool.poetry]
name = "atomic-red-team"
version = "0.1.0"
description = ""
authors = ["Maintainers <opensource@redcanary.com"]
readme = "README.md"
packages = [{include = "atomic_red_team"}]

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0"
jsonschema = "^4.19.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
