title: Atomic Red Team
description: |
  Atomic Red Team is a library of simple tests that every security team can execute to test their controls. Tests are
  focused, have few dependencies, and are defined in a structured format that be used by automation frameworks.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/redcanaryco/atomic-red-team
  repository_name: Atomic Red Team
